language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - composer test
